#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# start on boot

xrdb merge ~/.Xresources &
bash /home/artix/.config/polybar/launch.sh &
picom -f &
nitrogen --restore &
numlockx on &
xsetroot -cursor_name left_ptr
~/.Xmodmap &
light -S 30
#dunst &


bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap          4
bspc config split_ratio          0.50
#bspc config pointer_motion_interval	10

bspc config focus_follows_pointer	true

# layout
#bspc config initial_polarity first_child
bspc config borderless_monocle   false
bspc config single_monocle true
bspc config gapless_monocle      false

# borders
bspc config focused_border_color "#b48ead"
bspc config normal_border_color "#646870"
#bspc config unfocused_border_color "#d08770"

bspc rule -a Files desktop='^1' follow=on
bspc rule -a VSCodium desktop='^2' follow=on
bspc rule -a Chromium desktop='^3' follow=on
#bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a KotatogramDesktop desktop='^5' follow=on
bspc rule -a Alacritty desktop='^4' follow=on
bspc rule -a spotify-desktop desktop='^6' follow=on
